spring.config.import=file:./dev.env[.properties],file:dev.env[.properties]

server.port=8081
server.servlet.context-path=${DEFAULT_ROOT}
server.error.include-message=always

spring.application.name=markeazy

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=postgresql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.sql.init.schema-locations=classpath:/sql/
#spring.sql.init.mode=never

#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=15
spring.jpa.properties.hibernate.order_inserts=true

jwt.secret=${JWT_SECRET}
jwt.lifetime=${JWT_LIFETIME}

logging.charset.console=UTF-8
