spring.config.import=file:./.env[.properties],file:.env[.properties]

spring.application.name=markeazy
server.port=${BACKEND_PORT}
server.servlet.context-path=${DEFAULT_ROOT}
spring.servlet.multipart.enabled=true
server.error.include-message=always

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=postgresql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.platform=postgres
spring.sql.init.mode=never

#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=15
spring.jpa.properties.hibernate.order_inserts=true

spring.elasticsearch.uris=${ELASTICSEARCH_URL}



jwt.secret=${JWT_SECRET}
jwt.lifetime=${JWT_LIFETIME}

app.minio.access-key=${MINIO_USER}
app.minio.secret-key=${MINIO_PASSWORD}
app.minio.url=${MINIO_URL}
app.minio.bucket.product-image=images

logging.charset.console=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB